name: poc8003636/poc1
on:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2  # Replace with your desired region

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.5

    - name: Change Directory
      run: cd csop-aws-team-dev

    - name: Remove Existing Terraform Directory
      run: rm -rf .terraform

    - name: Terraform Version
      run: terraform --version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  plan:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.5

    - name: Change Directory
      run: cd csop-aws-team-dev

    - name: Remove Existing Terraform Directory
      run: rm -rf .terraform

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=planfile
      continue-on-error: true

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: csop-aws-team-dev/planfile

  apply:
    needs: plan
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run on manual dispatch
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.5

    - name: Change Directory
      run: cd csop-aws-team-dev

    - name: Remove Existing Terraform Directory
      run: rm -rf .terraform

    - name: Terraform Init
      run: terraform init

    - name: Download Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan
        path: csop-aws-team-dev/

    - name: Terraform Apply
      run: terraform apply -input=false "csop-aws-team-dev/planfile"
